---
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    # ✱ Forward these three flags straight to the controller ✱
    diff_drive_base_controller.publish_tf:        true
    diff_drive_base_controller.enable_odom_tf:    true
    diff_drive_base_controller.publish_odometry:  true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    sawyer_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

diff_drive_base_controller:
  ros__parameters:
    # ⇩  wheel joint names (front+rear each side)
    left_wheel_names: ["front_left_wheel", "rear_left_wheel"]
    right_wheel_names: ["front_right_wheel", "rear_right_wheel"]

    # ⇩ Measured hub-to-hub distance (m)
    wheel_separation: 0.45
    wheels_per_side: 2           # two driven wheels on each side
    wheel_radius: 0.10

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    # wheel_direction_multiplier: -1
    # Flip direction where needed
    # left_wheel_multiplier:  1.0     # ← flip only the wheel that’s reversed
    # right_wheel_multiplier:  -1.0

    publish_tf: false
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: agilex_diff_drive/base_link     # <- matches  URDF

    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]

    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    use_stamped_vel: false
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

sawyer_arm_controller:
  ros__parameters:
    joints: [right_j0, right_j1, right_j2,
             right_j3, right_j4, right_j5, right_j6]
    command_interfaces: [position]                     
    state_interfaces:   [position, velocity]

gripper_controller:
  ros__parameters:
    joints: [right_gripper_l_finger_joint]
             

    command_interfaces: [position]                     # required by JGPC